// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7wRNpF0giuW2hzihbZV7dvZDpQkmGug',
    appId: '1:97519894390:web:d3762d76f660378aefc457',
    messagingSenderId: '97519894390',
    projectId: 'ghina1-bda9e',
    authDomain: 'ghina1-bda9e.firebaseapp.com',
    storageBucket: 'ghina1-bda9e.firebasestorage.app',
    measurementId: 'G-Q89769B72K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7ahqnuROJ8QBXRTxA8Ir3ovkZDFybgI',
    appId: '1:97519894390:android:9a7b458cc19c13ebefc457',
    messagingSenderId: '97519894390',
    projectId: 'ghina1-bda9e',
    storageBucket: 'ghina1-bda9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs_EMtejvLJJcIBo5BZgpCrH-drIZetI0',
    appId: '1:97519894390:ios:9bb2e2da9df7a2e0efc457',
    messagingSenderId: '97519894390',
    projectId: 'ghina1-bda9e',
    storageBucket: 'ghina1-bda9e.firebasestorage.app',
    iosBundleId: 'com.example.ghina1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs_EMtejvLJJcIBo5BZgpCrH-drIZetI0',
    appId: '1:97519894390:ios:9bb2e2da9df7a2e0efc457',
    messagingSenderId: '97519894390',
    projectId: 'ghina1-bda9e',
    storageBucket: 'ghina1-bda9e.firebasestorage.app',
    iosBundleId: 'com.example.ghina1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA7wRNpF0giuW2hzihbZV7dvZDpQkmGug',
    appId: '1:97519894390:web:fa4716942a252b32efc457',
    messagingSenderId: '97519894390',
    projectId: 'ghina1-bda9e',
    authDomain: 'ghina1-bda9e.firebaseapp.com',
    storageBucket: 'ghina1-bda9e.firebasestorage.app',
    measurementId: 'G-RD2E5WP600',
  );
}
